name = "worker-super-lake-46a9"
main = "src/worker.js"
compatibility_date = "2023-09-18"
workers_dev = true

[triggers]
crons = [ "*/1 * * * *" ]

[env.development.vars]
TWILIO_SID='AC69bdd72215236cbf6dcae5d30d4dd28e'
TWILIO_TOKEN='e9f8762708aa50c617bc5c14b1536001'
TWILIO_NUMBER='+18559842297'
URL = "http://localhost:3000"
DELETEOODAPPTURL = "http://localhost:3000/api/deloodappt"
SYNCCALS = "http://localhost:3000/api/synccals"

[env.production.vars]
URL = "https://wearesnatch.vercel.app/"
DELETEOODAPPTURL = "https://wearesnatch.com/api/deloodappt"
SYNCCALS = "https://wearesnatch.com/api/synccals"

[env.preview.vars]
URL = "https://wearesnatch.vercel.app/"
DELETEOODAPPTURL = "https://wearesnatch.com/api/deloodappt"
SYNCCALS = "https://wearesnatch.com/api/synccals"
